#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# le nom de la route est "app_livre_number" (pas important pour le moment il n'y en qu'une)
app_livre_number:
  path: /livre/numero/{ref}
  controller: App\Controller\LivreController::numero